---
spring:
  banner:
    location: classpath:banner/banner.txt
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dannyvasquez22/Microservices-eureka
          searchPaths: spring-cloud-config
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8888