spring:
  application: 
    name: servicio-items
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/

server: 
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000

#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 10000