spring:
  application:
    name: servicio-productos

server:
  port: ${PORT:0}

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka