config:
  security:
    oauth:
      client:
        id: frontendapp
        secret: 12345
      jwt:
        key: algun_codigo_secreto_aeiou

spring:
  zipkin:
    baseUrl: http://zipkin-server:9411/
  rabbitmq:
    host: microservicios-rabbitmq38
