spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_springboot_cloud
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver

spring:
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddlAuto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
