spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_springboot_cloud?serverTimezone=America/Santiago&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddlAuto: create

logging:
  level:
    org:
      hibernate:
        SQL: debug
