spring:
  application:
    name: servicio-zuul-server
  sleuth:
    sampler:
      probability: 1.0    

server:
  port: 8090

eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    productos:
      serviceId: servicio-productos
      path: "/api/productos/**"
    items:
      serviceId: servicio-items
      path: "/api/items/**"
    usuarios:
      serviceId: servicio-usuarios
      path: "/api/usuarios/**"
    security:
      serviceId: servicio-oauth
      path: "/api/security/**"
      sensitiveHeaders: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000